import { ChangeDetectionStrategy, Component, computed, input, model } from '@angular/core';

let collapseSeq = 0;

/**
 * Accessible collapse: projected header (attribute `collapseHeader`) + default slot for body.
 * Two-way bind `collapsed` with `[collapsed]` / `(collapsedChange)` or `[(collapsed)]` on a writable field.
 */
@Component({
  selector: 'app-collapse',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'app-collapse',
    '[class.app-collapse--collapsed]': 'collapsed()',
    '[attr.role]': 'effectiveRole()',
    '[attr.aria-label]': 'ariaLabel()',
  },
  templateUrl: './collapse.component.html',
  styleUrl: './collapse.component.scss',
})
export class CollapseComponent {
  private readonly _uid = `app-collapse-${++collapseSeq}`;

  collapsed = model(false);

  /** Stable id for aria-controls / anchors; autogenerated if omitted */
  panelId = input<string | undefined>(undefined);

  showToggle = input(true);

  /** When set, defaults role to "region" unless `role` overrides */
  ariaLabel = input<string | undefined>(undefined);

  role = input<string | undefined>(undefined);

  expandAriaLabel = input('Expand section');
  collapseAriaLabel = input('Collapse section');

  effectiveRole = computed(() => {
    const explicit = this.role();
    if (explicit !== undefined && explicit !== '') return explicit;
    return this.ariaLabel() ? 'region' : undefined;
  });

  effectivePanelId = computed(() => this.panelId() ?? this._uid);

  toggleAriaLabel = computed(() =>
    this.collapsed() ? this.expandAriaLabel() : this.collapseAriaLabel(),
  );

  toggle(): void {
    this.collapsed.update((v) => !v);
  }
}
